### ISSUE TITLE
Optional

### ISSUE THREAD

**Issue by vnu** [vnu/vTweetz#3]
The following **optional** features are implemented:
- [x] When composing, you should have a countdown in the upper right for the tweet limit.
- [x] After creating a new tweet, a user should be able to view it in the timeline immediately without refetching the timeline from the network.
- [x] Retweeting and favoriting should increment the retweet and favorite count.
- [x] User should be able to unretweet and unfavorite and should decrement the retweet and favorite count.
- [x] Replies should be prefixed with the username and the reply_id should be set when posting the tweet,
- [x] User can load more tweets once they reach the bottom of the feed using infinite loading similar to the actual Twitter client.

**Comment by codepathreview** [comment]
:+1: Fantastic job with the submission - one of the best of the week. Awesome work with implement too many additional features. You did more than I expected. :tada: :star2: :100: 

With this assignment, we've now explored all the main patterns for building MVC clients! If this were 2009, you would be well on your way to building most apps that you could find in the app store. Over the next few weeks, we'll be focusing on custom views and view controllers to implement the interactions and visual effects that we find in more modern iOS apps.

We have a detailed [Project 3 Feedback Guide](http://courses.codepath.com/snippets/intro_to_ios/feedback_guides_swift/project_3_feedback.md) which covers the best practices for implementing this assignment. Read through the feedback guide point-by-point to determine ways you might be able to improve your submission. You should consider going back and implementing these improvements as well. Keep in mind that one of the most important parts of iOS development is learning the correct patterns and conventions.

If you have any particular questions about the assignment or the feedback, feel free to reply here or email us at support@codepath.com

This was a very challenging assignment, congrats on completing it successfully!
